"""
Atlas Sanctum — Phase IV Schema
DigitalTwin, InventionProposal, ExperimentRun, PrototypeStatus
"""
from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any
import uuid


def _uid() -> str:
    return str(uuid.uuid4())


class PrototypeStatus(str, Enum):
    IDEA = "idea"
    DESIGNED = "designed"
    PROTOTYPING = "prototyping"
    TESTING = "testing"
    VALIDATED = "validated"
    SCALING = "scaling"


class ExperimentStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETE = "complete"
    FAILED = "failed"


@dataclass
class DigitalTwin:
    """A live digital model of a physical asset or system."""
    id: str = field(default_factory=_uid)
    name: str = ""
    asset_id: str = ""            # ID of the physical entity in the knowledge graph
    model_type: str = ""          # e.g. "water_pump", "solar_array", "crop_field"
    state: dict[str, Any] = field(default_factory=dict)
    last_synced: datetime = field(default_factory=datetime.utcnow)
    node_id: str = ""


@dataclass
class InventionProposal:
    """A structured proposal generated by the invention engine."""
    id: str = field(default_factory=_uid)
    title: str = ""
    problem: str = ""
    proposed_solution: str = ""
    required_resources: list[str] = field(default_factory=list)
    estimated_impact: str = ""
    domain: str = ""
    status: PrototypeStatus = PrototypeStatus.IDEA
    created_at: datetime = field(default_factory=datetime.utcnow)
    opportunity_id: str = ""
    node_id: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class ExperimentRun:
    """A tracked experiment against a digital twin or simulation."""
    id: str = field(default_factory=_uid)
    name: str = ""
    twin_id: str = ""
    hypothesis: str = ""
    parameters: dict[str, Any] = field(default_factory=dict)
    result: dict[str, Any] = field(default_factory=dict)
    status: ExperimentStatus = ExperimentStatus.PENDING
    started_at: datetime | None = None
    completed_at: datetime | None = None
    node_id: str = ""
